// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecfhbbydhygwfxnoqnpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZmhiYnlkaHlnd2Z4bm9xbnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTMyNDcsImV4cCI6MjA3Mzg2OTI0N30.XbPBeOadUXqNeZBPDZ3M1oG11zAhZl2dDdk3jK-iezY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});